version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    #    commit-message:
    #      prefix: '[skip ci]'
    labels:
      - 'type: dependencies 🧷'
      # Add Kodiak `merge.automerge_label`
      - 'automerge 🤞'
